import Head from "next/head";
import { useState } from "react";
import Nav from "../Components/nav";
import Me from "../Components/me";
import Social from "../Components/social";
import ImageDev from "../Components/ImageDev";
import Services from "../Components/Services";
import Proyects from "../Components/Proyects";
import LanguageSelector from "../Components/languageSelector";

export default function Home(props) {
  const [dark, setDark] = useState(false);
  const { index, me, services, proyects, nav } = props;

  return (
    <div className={dark ? "dark" : ""}>
      <Head>
        <title>{index.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-5 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen  dark:text-white">
          <div>
            <Nav setDark={setDark} dark={dark} nav={nav} />
            <LanguageSelector  />
          </div>


          <Social />
          <ImageDev />
        </section>
        <Services services={services} />
        <Proyects proyects={proyects} />
      </main>
    </div>
  );
}

export async function getStaticProps({ locale }) {
  const res = await import(`../lang/${locale}.json`);

  return {
    props: {
      index: res.default.index,
      me: res.default.me,
      services: res.default.services,
      proyects: res.default.proyects,
      nav: res.default.nav,
    },
  };
}
