import Head from "next/head";
import { useState } from "react";
import Nav from "../Components/nav";
import Me from "../Components/me";
import Social from "../Components/social";
import ImageDev from "../Components/imageDev";
import Services from "../Components/services";
import Proyects from "../Components/proyects";
 


export default function Home(props) {
  const [dark, setDark] = useState(false);
  const {index, nav} = props;



  return (
    <div className={dark ? "dark" : "" }>
      <Head>
        <title>{index.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen  dark:text-white">
        <Nav setDark={setDark} dark={dark}/>


        <Me hi={nav}/>
        <Social/>
        <ImageDev/>  
        </section>
       <Services/>
       <Proyects/>
      </main>
    </div>
  );
}


export async function getStaticProps({ locale }) {
    
  const res = await import(`../lang/${locale}.json`);

return {
  
   props:{
    index: res.default.index,
    nav: res.default.nav,
   }
};
}
